#!/bin/sh
set -eu

psql \
  -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  <<SQL

CREATE ROLE job_service
  LOGIN
  PASSWORD '${JOB_DB_PASSWORD}';

CREATE ROLE hire_service
  LOGIN
  PASSWORD '${HIRE_DB_PASSWORD}';

CREATE ROLE career_service
  LOGIN
  PASSWORD '${CAREER_DB_PASSWORD}';

GRANT CONNECT ON DATABASE ${POSTGRES_DB}
TO job_service, hire_service, career_service;

GRANT USAGE ON SCHEMA job
TO job_service;

GRANT USAGE ON SCHEMA hire
TO hire_service;

GRANT USAGE ON SCHEMA career
TO career_service;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA job
TO job_service;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA hire
TO hire_service;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA career
TO career_service;

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_USER}
IN SCHEMA job
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO job_service;

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_USER}
IN SCHEMA hire
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO hire_service;

ALTER DEFAULT PRIVILEGES
FOR ROLE ${POSTGRES_USER}
IN SCHEMA career
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES
TO career_service;

SQL