apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-asset-service
spec:
  template:
    spec:
      containers:
        - name: job-asset-service
          env:
            - name: OTEL_SERVICE_NAME
              value: job-asset-service
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://otel-collector:4318/v1/traces
