apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - istio/gateway.yaml
  - istio/virtual-service.yaml
  - otel/collector.yaml

patches:
  - path: otel/app-otel-patch.yaml
